apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: juice-shop
spec:
  host: app-20.232.62.166.nip.io
  tls:
  -naem: nap-policy
    secret: juice-shop-secret
  ingressClassName: glonganezi-nginx-ingress  
  upstreams:
  - name: juice-shop
    service: juice-shop-svc
    port: 80
  routes:
  - path: /
    action:
      proxy: 
        upstream: juice-shop
        requestHeaders:
          pass: true


